### ISSUE TITLE
Permissions Laraval

### ISSUE THREAD

**Issue by Codepowders** [wmellema/docker-laravel#1]
Access rights to safe files denied. Not executable.

**Comment by wmellema** [comment]
@Codepowders Safe files? Which are you talking about?

**Comment by Codepowders** [comment]
Ow ik bedoelde dat ik toen geen dingen kon opslaan. Dat er geen rechten
voor waren. Maar bij mij was dat al opgelost. Ik dacht dat je het als issue
op github wou hebbeb.

Op 20 feb. 2018 21:43 schreef "Wouter Mellema" <notifications@github.com>:

**Comment by wmellema** [comment]
Issue already fixed. This can happen sometimes, but there is a fix in the README documentation

Closing issue
